# name: Frontend Testing
# on:
#   pull_request:
#     branches: [ development ]
# jobs:
#   cypress-test:
#     runs-on: ubuntu-latest
#     container:
#       image: cypress/browsers:node16.5.0-chrome94-ff93
#       options: --user 1001
#     steps:
#       - uses: actions/checkout@v3
#       - name: Install and Verify Cypress
#         run: |
#           npm ci
#           $(npm bin)/cypress verify
     
#       - name: Run Cypress tests
#         run: npm run all-tests
#         continue-on-error: false
#       - name: Copy test report from cypress to Github Pages
#         run: |
#           mkdir report-folder
#           cp -r cypress/reports/index.html report-folder

#       - name: Deploy report to Github Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_branch: gh-pages
#           publish_dir: ./report-folder
